wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.30
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.2
    t:
      4: 3.8.2
      5: 0.10.30
      8:
      - 3
      - 5
epochs:
  desc: null
  value: 5000
learning_rate:
  desc: null
  value: 0.01
